accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'sign_in/$', views.sign_in, name='sign_in'),
    url(r'sign_up/$', views.sign_up, name='sign_up'),
    url(r'sign_out/$', views.sign_out, name='sign_out'),
    url(r'profile/$', views.profile, name='profile'),
    url(r'profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'profile/edit_avatar/$', views.edit_avatar, name='edit_avatar'),
    url(r'profile/change_password/$',
        views.change_password, name='change_password'),
]

usermanager/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    url(r'^$', views.home, name='home'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    username = None
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254, unique=True)
    date_of_birth = models.DateField(null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    avatar = models.ImageField(null=True, blank=True, upload_to='avatars')
    city = models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    favorite_animal = models.CharField(max_length=100, null=True, blank=True)
    hobbies = models.CharField(max_length=255, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def get_username(self):
        return self.email

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

accounts/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import User

DATE_INPUT_FORMATS = ['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y']


class DateInput(forms.DateInput):
    input_type = 'date'
    format = DATE_INPUT_FORMATS


class CreateUserForm(UserCreationForm):
    email2 = forms.EmailField(label="Confirm Email Address",
                              required=False,
                              validators=[validators.EmailValidator()],
                              widget=forms.EmailInput
                              )

    class Meta(UserCreationForm):
        model = User
        fields = ('email', 'email2', 'first_name', 'last_name',
                  'password1', 'password2')

    def clean(self):
        cleaned_data = super(CreateUserForm, self).clean()
        try:
            email2 = cleaned_data['email2']
        except KeyError:
            raise forms.ValidationError(
                'Please confirm your email address!')
        else:
            if cleaned_data['email'].lower() != email2.lower():
                raise forms.ValidationError('Email Addresses do not match!')


class UpdateUserForm(UserChangeForm):
    password = None
    email2 = forms.EmailField(label="Confirm Email Address",
                              required=False,
                              validators=[validators.EmailValidator()],
                              widget=forms.EmailInput
                              )

    class Meta(UserChangeForm):
        model = User
        fields = ('email', 'email2', 'first_name', 'last_name',
                  'date_of_birth', 'bio', 'avatar', 'city', 'state',
                  'country', 'favorite_animal', 'hobbies', )
        widgets = {
            'date_of_birth': DateInput()
        }

    def clean(self):
        cleaned_data = super(UpdateUserForm, self).clean()
        try:
            email2 = cleaned_data['email2']
        except KeyError:
            raise forms.ValidationError(
                'Please confirm your email address!')
        else:
            if cleaned_data['email'].lower() != email2.lower():
                raise forms.ValidationError('Email Addresses do not match!')

    def clean_bio(self):
        bio = self.cleaned_data['bio']
        if len(bio) < 10:
            raise forms.ValidationError(
                'Bio must be more than 10 characters!')
        return bio


class AvatarEditForm(forms.Form):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    rotate = forms.FloatField(widget=forms.HiddenInput())
    scaleX = forms.FloatField(widget=forms.HiddenInput())
    scaleY = forms.FloatField(widget=forms.HiddenInput())

accounts/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import (AuthenticationForm,
                                       PasswordChangeForm)
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.contrib import messages

from PIL import Image

from . import forms


def sign_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if form.user_cache is not None:
                user = form.user_cache
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('accounts:profile'))
                else:
                    messages.error(
                        request,
                        "That user account has been disabled."
                    )
            else:
                messages.error(
                    request,
                    "Username or password is incorrect."
                )
    return render(request, 'accounts/sign_in.html', {'form': form})


def sign_up(request):
    form = forms.CreateUserForm()
    if request.method == 'POST':
        form = forms.CreateUserForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password1']
            )
            login(request, user)
            messages.success(
                request,
                "You're now a user! You've been signed in, too."
            )
            return HttpResponseRedirect(reverse('accounts:profile'))
    return render(request, 'accounts/sign_up.html', {'form': form})


@login_required
def sign_out(request):
    logout(request)
    messages.success(request, "You've been signed out. Come back soon!")
    return HttpResponseRedirect(reverse('home'))


@never_cache
@login_required
def profile(request):
    return render(request, 'accounts/profile.html')


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = forms.UpdateUserForm(request.POST,
                                    request.FILES or None,
                                    instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(
                request,
                'Your profile is updated!'
            )
            return HttpResponseRedirect(reverse('accounts:profile'))
    else:
        form = forms.UpdateUserForm(instance=request.user)

    context = {
        'form': form
    }
    return render(request, 'accounts/edit_profile.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            messages.success(
                request,
                'Password updated! Please login with your new password')
            return HttpResponseRedirect(reverse('accounts:sign_in'))
    else:
        form = PasswordChangeForm(user=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/change_password.html', context)


@login_required
def edit_avatar(request):
    avatar = request.user.avatar
    if request.method == 'POST':
        form = forms.AvatarEditForm(request.POST,
                                    request.FILES or None)
        if form.is_valid():
            x = form.cleaned_data.get('x')
            y = form.cleaned_data.get('y')
            width = form.cleaned_data.get('width')
            height = form.cleaned_data.get('height')
            rotate = form.cleaned_data.get('rotate')
            image = Image.open(avatar)
            image = image.crop((x, y, width + x, height + y))
            image = image.rotate(-rotate, expand=True)
            if form.cleaned_data.get('scaleX') == -1:
                image = image.transpose(Image.FLIP_LEFT_RIGHT)
            image.save(avatar.path)
            return HttpResponseRedirect(reverse('accounts:profile'))
    else:
        form = forms.AvatarEditForm()

    context = {
        'form': form,
        'avatar': avatar
    }
    return render(request, 'accounts/edit_avatar.html', context)

accounts/templates/accounts/change_password.html
{% extends "layout.html" %}

{% load static %}

{% block title %}Change Password {{ super }}{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/strengthify.min.css' %}">
    <script src="{% static 'js/jquery.strengthify.min.js' %}"></script>
{% endblock %}

{% block body %}
    <form id="change_password" method="POST" action="{% url 'accounts:change_password' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button-primary" value="Save">
    </form>
    <script type="text/javascript">
        $(document.getElementById("change_password").elements["new_password1"]).strengthify({
            zxcvbn: 'https://cdn.rawgit.com/dropbox/zxcvbn/master/dist/zxcvbn.js',
            drawTitles: true,
            drawMessage: true
        })
        $(document.getElementById("change_password").elements["new_password2"]).strengthify({
            zxcvbn: 'https://cdn.rawgit.com/dropbox/zxcvbn/master/dist/zxcvbn.js',
            drawTitles: true,
            drawMessage: true
        })
    </script>
{% endblock %}

accounts/templates/accounts/edit_avatar.html
{% extends "layout.html" %}

{% load static %}

{% block title %}Edit Avatar | {{ block.super }}{% endblock %}


{% block header %}
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="{% static "js/cropper.min.js" %}"></script><!-- Cropper.js is required -->
    <link  href="{% static "css/cropper.min.css" %}" rel="stylesheet">
{% endblock %}


{% block body %}
    <img id="image" src="{{ avatar.url }}">
    <br>
    <button type="button" class="button-primary zoom-in">Zoom In</button>
    <button type="button" class="button-primary zoom-out">Zoom Out</button>
    <button type="button" class="button-primary rotate-cw">Rotate Clockwise</button>
    <button type="button" class="button-primary rotate-ccw">Rotate Counterclockwise</button>
    <button type="button" class="button-primary mirror">Mirror</button>
    <br>

    <form method="POST" id="avatar_edit">
        {% csrf_token %}
        {{ form }}

        <button type="button" class="button-primary submit">Save Changes</button>
    </form>

    <script>
        $(function () {
            var $image = $("#image");
            $image.cropper({
                viewMode: 1,
                minCropBoxWidth: 200,
                minCropBoxHeight: 200
            });
            $(".zoom-in").click(function () {
                $image.cropper("zoom", 0.1);
            });
            $(".zoom-out").click(function () {
                $image.cropper("zoom", -0.1);
            });
            $(".rotate-cw").click(function () {
                $image.cropper("rotate", 90);
            });
            $(".rotate-ccw").click(function () {
                $image.cropper("rotate", -90);
            });
            $(".mirror").click(function () {
                var cropData = $image.cropper("getData")
                if (cropData['scaleX'] == 1) {
                    $image.cropper("scale", -1, 1);
                } else {
                    $image.cropper("scale", 1);
                }
            });
            $(".submit").click(function () {
                var cropData = $image.cropper("getData");
                $("#id_x").val(cropData["x"]);
                $("#id_y").val(cropData["y"]);
                $("#id_width").val(cropData["width"]);
                $("#id_height").val(cropData["height"]);
                $("#id_rotate").val(cropData["rotate"]);
                $("#id_scaleX").val(cropData["scaleX"]);
                $("#id_scaleY").val(cropData["scaleY"]);
                $("#avatar_edit").submit();
            });
        });
    </script>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends "layout.html" %}

{% load static %}

{% block title %}Edit Profile | {{ user.first_name }}{{ super }}{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'js/trumbowyg/dist/ui/trumbowyg.min.css' %}">
    <script type="text/javascript" src="{% static 'js/global.js' %}"></script>
    <script src="{% static 'js/trumbowyg/dist/trumbowyg.min.js' %}"></script>
{% endblock %}

{% block body %}
<form method="POST" enctype="multipart/form-data" action="{% url 'accounts:edit_profile' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Save">
</form>
<script>
    $('textarea').trumbowyg();
</script>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "layout.html" %}
{% load static %}

{% block title %}{%if user.first_name %}{{ user.first_name }}{% else %}Profile{% endif %} | {{ block.super }}{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
{% endblock %}

{% block body %}
    {% if user.is_authenticated %}
        {% if user.avatar %}
            <div class="image-cropper">
                 <img class="circle--primary--avatar profile-image" src="{{ user.avatar.url }}" alt="{{ user }} avatar">
                <a href="{% url 'accounts:edit_avatar' %}" type="button" class="button-primary edit">Edit</a>
            </div>
        {% endif %}
        <h2>Account details</h2>
        <p>Name: {{ user.first_name }} {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        {% if user.date_of_birth %}
            <p>Date of birth: {{ user.date_of_birth }}</p>
        {% endif %}
        {% if user.city %}
            <p>City: {{ user.city }}</p>
        {% endif %}
        {% if user.state %}
            <p>State: {{ user.state }}</p>
        {% endif %}
        {% if user.country %}
            <p>Country: {{ user.country }}</p>
        {% endif %}
        {% if user.favorite_animal %}
            <p>Favorite Animal: {{ user.favorite_animal }}</p>
        {% endif %}
        {% if user.hobbies %}
            <p>Hobbies: {{ user.hobbies }}</p>
        {% endif %}
        {% if user.bio %}
            <h2>Bio</h2>
            <p>{{ user.bio|safe }}</p>
        {% endif %}
    {% endif %}
{% endblock %}

accounts/templates/accounts/sign_in.html
{% extends "layout.html" %}

{% block title %}Sign In | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_in' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign In">
</form>
{% endblock %}

accounts/templates/accounts/sign_up.html
{% extends "layout.html" %}
{% load static %}
{% block title %}Sign Up | {{ super }}{% endblock %}
{% block header %}
    <link rel="stylesheet" href="{% static 'css/strengthify.min.css' %}">
    <script src="{% static 'js/jquery.strengthify.min.js' %}"></script>
{% endblock %}

{% block body %}
    <form id="sign_up" method="POST" action="{% url 'accounts:sign_up' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button-primary" value="Sign Up">
    </form>
    <script type="text/javascript">
        $(document.getElementById("sign_up").elements["password1"]).strengthify({
            zxcvbn: 'https://cdn.rawgit.com/dropbox/zxcvbn/master/dist/zxcvbn.js',
            drawTitles: true,
            drawMessage: true
        })
        $(document.getElementById("sign_up").elements["password2"]).strengthify({
            zxcvbn: 'https://cdn.rawgit.com/dropbox/zxcvbn/master/dist/zxcvbn.js',
            drawTitles: true,
            drawMessage: true
        })
    </script>
{% endblock %}